apiVersion: apps/v1
kind: Deployment
metadata:
  name: kr-hospital-api
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /kr-openapi
            - name: BASE_URL
              value: /kr-openapi-ui
