apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: kr-hospital-xfe-content
spec:
  microFrontend: kr-hospital-xfe
  element: kr-hospital-app
  attributes:
    - name: base-path
      value: /kr-hospital/
    - name: api-base
      value: /kr-api
    - name: hospital-id
      value: hospital-ba
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?kr-hospital(/.*)?$"
